export const PRODUCTS = [
  {
    id: "duo", name: "Nimed Mosquito Duo 40ml", origin: "Made in Italy", cat: "Protective Care",
    tagline: "The only 2-in-1 mosquito product on the market",
    desc: "Repellent cream + soothing balm in one tube. Eucalyptus & citronella. Plant-based, DEET-free.",
    retail: 42, buyPrice: 31.50, profit: 10.50,
    thumb: "/img/duo-1.png", gallery: ["/img/duo-1.png", "/img/duo-2.png"],
    why: [
      "No direct competitor in UAE pharmacies — you own the category",
      "Two selling moments: before the bite AND after the itch",
      "Parents prefer plant-based, DEET-free for children",
      "Counter display impulse buy — sells itself at the register",
      "Peak season: March–November (9 months of demand)",
    ],
  },
  {
    id: "pads", name: "Nimed Underpads XL · 90×180cm", origin: "Made in Italy", cat: "Continence Care",
    tagline: "The only full-bed-coverage disposable underpad",
    desc: "20 sheets/pack. Hypoallergenic. Waterproof back. Multi-layer absorption.",
    retail: 99, buyPrice: 74.25, profit: 24.75,
    thumb: "/img/pads-1.png", gallery: ["/img/pads-1.png"],
    why: [
      "90×180cm = full bed. No overlapping, no gaps, no leaks",
      "No competitor offers this size — unique in UAE",
      "Families with elderly, post-surgery, hospital discharge",
      "Stock near adult diapers & incontinence section",
      "Highest absolute profit per unit in the entire range",
    ],
  },
  {
    id: "tea", name: "Planta Lax Tea · 20 Bags", origin: "Made in Austria", cat: "Digestive Health",
    tagline: "The natural alternative to pharmaceutical laxatives",
    desc: "Senna, cascara bark & chamomile. MOH Reg# 1890-2547-1-C6. Pharmacist-formulated.",
    retail: 46, buyPrice: 34.50, profit: 11.50,
    thumb: "/img/tea-1.png", gallery: ["/img/tea-1.png", "/img/tea-2.png", "/img/tea-3.png", "/img/tea-4.png"],
    why: [
      "Competes with Dulcolax — herbal, gentle, no cramping",
      "MOH certified gives credibility over wellness teas",
      "Repeat purchase: box lasts ~20 days, customers return monthly",
      "Your highest-margin digestive recommendation",
      "Year-round demand, spikes during Ramadan & holidays",
    ],
  },
  {
    id: "tabs", name: "Fittydent Cleaning Tablets · 32s", origin: "Made in Austria", cat: "Dental Care",
    tagline: "The only pH-9 balanced denture cleaner",
    desc: "Zinc-free, gluten-free, vegan. Gentle on gums. Premium Corega alternative.",
    retail: 30, buyPrice: 22.50, profit: 7.50,
    thumb: "/img/tabs-1.png", gallery: ["/img/tabs-1.png"],
    why: [
      "Premium alternative to Corega — gentler pH-9 formula",
      "Denture wearers buy every month — pure recurring revenue",
      "Sits alongside existing denture section — no rearrangement",
      "Growing elderly population in UAE = expanding market",
      "Dentist referral potential — prosthodontists recommend by name",
    ],
  },
  {
    id: "trio", name: "Mosquito Trio Spray 100ml", origin: "Made in Italy", cat: "Protective Care",
    tagline: "3-in-1: protection, soothing & skin nourishment",
    desc: "Eucalyptus, citronella & aloe vera. Up to 4 hours natural protection.",
    retail: 54, buyPrice: 40.50, profit: 13.50,
    thumb: "/img/trio-1.png", gallery: ["/img/trio-1.png"],
    why: [
      "Spray format complements the Duo cream — sell both together",
      "Aloe vera adds skin care benefit beyond repelling",
      "Perfect for outdoor: camping, garden dining, BBQs",
      "Family-safe, natural ingredients, no harsh chemicals",
      "Complete Mosquito Kit cross-sell doubles basket size",
    ],
  },
  {
    id: "soap", name: "Amira Honey Milk Soap 100g", origin: "Made in Germany", cat: "Dermatology",
    tagline: "Original formula for sensitive & eczema-prone skin",
    desc: "Paraben-free. Sulfate-free. Honey & milk proteins. Naturkosmetik Labs.",
    retail: 15, buyPrice: 11.25, profit: 3.75,
    thumb: "/img/soap-1.png", gallery: ["/img/soap-1.png"],
    why: [
      "Dermatology shelf product — cross-sell with skin prescriptions",
      "Lowest price point = easiest customer yes in the range",
      "Daily-use consumable — highest repeat purchase rate",
      "Growing demand for clean, paraben-free skincare in UAE",
      "German quality at accessible price builds pharmacy trust",
    ],
  },
];

export const BONUS = [
  { buy: 6, free: 1, label: "6+1", total: 7 },
  { buy: 12, free: 3, label: "12+3", total: 15 },
  { buy: 25, free: 7, label: "25+7", total: 32 },
  { buy: 50, free: 15, label: "50+15", total: 65 },
  { buy: 100, free: 35, label: "100+35", total: 135 },
];
