(()=>{
 'use strict';const sb=window.PSC_SUPABASE,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={agreement:'Signed supply agreement',account_form:'Account opening form',registration:'Company / institutional registration',vat:'VAT certificate',buyers:'Authorized ordering contacts',billing:'Billing, delivery & invoice instructions',vendor:'Their vendor-registration requirements',credit:'Credit application / decision (only if requested)'};
 const states={internal_pending:'PSC document not ready',pending:'Awaiting customer',received:'Received — needs review',verified:'Verified by PSC',not_applicable:'Not applicable'};
 async function call(body){const r=await sb.functions.invoke('procurement-mail',{body});let code=r.data?.error;try{if(r.error&&!code)code=(await r.error.context.json()).error}catch{}if(r.error||code)throw new Error(({verify_all_required_items:'Verify all required items and record evidence before approving.',final_pack_and_confirmation_required:'The agreement and account form must be final before you record the pack as sent.',onboarding_changed_reload:'This record changed. Reopen it before saving.',onboarding_draft_outdated:'The checklist changed. This reminder is outdated and cannot be sent.',onboarding_paused_for_reply:'A new email arrived. Review it and update the checklist before resuming.',storage_operation_failed:'Could not save. Reopen the record; check for a pending email send before retrying.'}[code])||String(code||'Onboarding unavailable. Please try again.').replace(/_/g,' '));return r.data;}
 async function mount(h){
  if(h.dataset.mounted||window.PSC_IS_DEMO_ACCOUNT?.())return;h.dataset.mounted='1';const contact_id=h.dataset.onboardingContact;
  async function refresh(){h.innerHTML='<p>Loading onboarding…</p>';try{
   const {data:b,error}=await sb.from('psc_onboarding').select('*').eq('contact_id',contact_id).maybeSingle();if(error)throw new Error('Onboarding could not load.');if(!h.isConnected)return;
   h.innerHTML='<h2>Onboarding / account opening</h2><p>Track the documents, ordering authority and account arrangements here. Approval does not itself grant credit or release procurement.</p>';
   if(!b){h.insertAdjacentHTML('beforeend','<p>No onboarding started. Existing contacts are not enrolled automatically.</p><button class="button primary" data-start>Start onboarding checklist</button><p data-feedback role="status"></p>');h.querySelector('[data-start]').onclick=()=>run({action:'onboarding_start',approve:true});return;}
   const [jobs,drafts]=await Promise.all([sb.from('psc_onboarding_reminders').select('*').eq('onboarding_id',b.id).order('step'),sb.from('psc_mail_drafts').select('*').eq('onboarding_id',b.id).order('created_at',{ascending:false})]);if(jobs.error||drafts.error)throw new Error('Could not load onboarding reminders.');
   const label={preparing:'Preparing the pack',waiting:'Waiting for customer',paused:'Paused — review needed',review:'Ready for PSC review',active:'Onboarding approved'}[b.status];
   h.insertAdjacentHTML('beforeend',`<p><b>${esc(label)}</b>${b.last_error?' · '+esc(b.last_error.replace(/_/g,' ')):''}</p><form class="wsForm" data-checklist>${Object.keys(labels).map(k=>`<fieldset class="wsNote"><legend>${labels[k]}</legend><label>Status<select name="${k}" ${b.status==='active'?'disabled':''}>${Object.entries(states).filter(([v])=>v!=='not_applicable'||['vat','vendor','credit'].includes(k)).filter(([v])=>v!=='internal_pending'||['agreement','account_form'].includes(k)).map(([v,t])=>`<option value="${v}" ${b.items[k].status===v?'selected':''}>${t}</option>`).join('')}</select></label><label>Evidence / document reference / reason<textarea name="${k}_note" rows="2" maxlength="1500" placeholder="Where the signed document is saved, what was checked, or why this is not applicable" ${b.status==='active'?'disabled':''}>${esc(b.items[k].note)}</textarea></label></fieldset>`).join('')}<label>Account-opening notes<textarea name="notes" maxlength="3000" ${b.status==='active'?'disabled':''}>${esc(b.notes)}</textarea></label>${b.status!=='active'?'<button class="button primary">Save checklist</button>':''}</form><p>No document upload or e-signature is performed here yet. Keep originals in the controlled correspondence record and record their references above.</p><div class="wsActions">${b.status!=='active'&&!b.pack_sent_at?'<button data-pack>Record final pack as sent</button>':''}${b.status==='waiting'?'<button data-pause>Pause reminders</button>':''}${['paused','review','preparing'].includes(b.status)&&b.pack_sent_at?'<button data-resume>Resume after review</button>':''}${b.status!=='active'?'<button data-activate>Approve completed onboarding</button>':''}</div><h3>Scheduled reminder drafts</h3><p>After you record the final pack as sent: reminders at 9am Dubai time, 3 and 7 working days later (Monday–Friday; holidays not configured). Each becomes a draft and a task for you, never an automatic send. A new email from this exact contact pauses the sequence.</p>${jobs.data.map(j=>`<p>Day ${j.step} · ${esc(new Date(j.due_at).toLocaleString('en-GB',{timeZone:'Asia/Dubai'}))} Dubai · ${esc(j.status)}</p>`).join('')||'<p>Not scheduled yet.</p>'}${drafts.data.map(d=>`<article class="wsNote"><b>${esc(d.subject)}</b><p>${esc(d.recipient)} · ${esc(d.status)}${d.onboarding_revision!==b.revision?' · Outdated — do not send':''}</p><details><summary>Read reminder</summary><p class="wsPre">${esc(d.body_text)}</p></details>${d.status==='draft'&&d.onboarding_revision===b.revision&&b.status==='waiting'?`<button data-send="${esc(d.id)}">Review & approve send</button>`:''}</article>`).join('')}<p data-feedback role="status"></p>`);
   h.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),items=Object.fromEntries(Object.keys(labels).map(k=>[k,{status:f.get(k),note:f.get(k+'_note')}]));run({action:'onboarding_save',revision:b.revision,items,notes:f.get('notes')});};
   h.querySelector('[data-pack]')?.addEventListener('click',()=>{if(confirm('Have you sent the FINAL agreement and account-opening pack to this customer? This records your action; it does not send attachments. Save checklist changes first.'))run({action:'onboarding_pack_sent',revision:b.revision,approve:true})});
   h.querySelector('[data-pause]')?.addEventListener('click',()=>run({action:'onboarding_pause',revision:b.revision}));
   h.querySelector('[data-resume]')?.addEventListener('click',()=>{if(confirm('Have you reviewed all replies and saved the current outstanding items? Previous reminder drafts remain invalid.'))run({action:'onboarding_resume',revision:b.revision,approve:true})});
   h.querySelector('[data-activate]')?.addEventListener('click',()=>{if(confirm('Confirm you verified the signed documents, ordering contacts and payment arrangements. This does not grant credit or authorize procurement.'))run({action:'onboarding_activate',revision:b.revision,approve:true})});
   h.querySelectorAll('[data-send]').forEach(button=>button.onclick=()=>{const d=drafts.data.find(d=>d.id===button.dataset.send);if(confirm('From: sales@pharmaservice.ae\nTo: '+d.recipient+'\n\n'+d.body_text+'\n\nApprove sending this exact reminder?'))run({action:'send',draft_id:d.id,approve:true})});
  }catch(e){h.innerHTML='<h2>Onboarding</h2><p>'+esc(e.message)+'</p><button data-retry>Retry</button>';h.querySelector('[data-retry]').onclick=refresh;}}
  async function run(body){h.querySelectorAll('button').forEach(b=>b.disabled=true);try{await call({...body,contact_id});const stage=document.querySelector('[data-ws-contact] [name=journey_stage]');if(stage&&['onboarding_start','onboarding_activate'].includes(body.action))stage.value=body.action==='onboarding_start'?'onboarding':'customer';await refresh();}catch(e){h.querySelector('[data-feedback]').textContent=e.message;}finally{h.querySelectorAll('button').forEach(b=>b.disabled=false)}}
  refresh();
 }
 function apply(){const form=document.querySelector('[data-ws-contact]'),id=form?.querySelector('[name=id]')?.value;if(!id||document.querySelector('[data-onboarding-contact]'))return;const h=document.createElement('section');h.className='wsPanel';h.dataset.onboardingContact=id;form.closest('.wsSplit').after(h);mount(h);}
 window.PSC_ENHANCEMENTS.createObserver(apply).observe(document.body,{childList:true,subtree:true});apply();
})();
