(()=>{
 'use strict';const sb=window.PSC_SUPABASE,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const errors={outreach_alias_not_ready:'Google has not verified outreach@pharmaservice.ae as a Send mail as address on info@. Add the alias and its Gmail send-as identity, then check again.',reconnect_required:'Reconnect the PSC mailbox in Settings, then return here.',internal_test_required:'Send and receive the internal sender test first.',setup_confirmation_required:'Confirm the test arrived and sender authentication passed.',campaign_changed_or_setup_incomplete:'The campaign changed or setup is incomplete. Refresh, check setup and review it again.',rate_limited:'Please wait before trying again.',campaign_already_approved:'This campaign is already approved. Check History for progress.',choose_1_to_500_contacts:'Choose between 1 and 500 subscribed contacts for this campaign.',invalid_campaign:'Check the subject, opening note and sender. Older info@ drafts should be opened as a new editable copy.',invalid_campaign_link:'The campaign link must be a secure pharmaservice.ae address.'};
 async function call(body){const r=await sb.functions.invoke('send-mail-campaign',{body});let code=r.data?.error;if(r.error&&!code){try{code=(await r.error.context.json()).error}catch{}}if(r.error||code)throw new Error(errors[code]||'Outreach could not complete this action. Refresh and retry.');return r.data}
 function dialog(title,body,ready){const d=document.createElement('dialog');d.className='wsDialog';d.innerHTML=`<div class="wsDialogHead"><h2>${title}</h2><button data-close aria-label="Close">×</button></div>${body}<p role="status" data-error></p>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();ready(d);return d}
 async function run(d,fn){const b=d.querySelector('[data-confirm]');if(b)b.disabled=true;d.querySelector('[data-error]').textContent='Working…';try{await fn()}catch(e){d.querySelector('[data-error]').textContent=e.message}finally{if(b?.isConnected)b.disabled=false}}
 window.PSC_OUTREACH_REVIEW=async id=>{
  const d=dialog('Review campaign','<p data-review>Loading the saved campaign…</p>',()=>{});
  try{const r=await call({action:'review',campaign_id:id}),c=r.campaign;
   if(!d.isConnected)return;
   d.querySelector('[data-review]').outerHTML=`<div><p><b>From:</b> Pharma Service &lt;outreach@pharmaservice.ae&gt;<br><b>Reply-to:</b> outreach@pharmaservice.ae</p><h3>${esc(c.subject)}</h3><p class="wsPre">${esc(c.intro)}</p><p><a target="_blank" rel="noopener noreferrer" href="${esc(c.cta_url)}">${esc(c.cta_label)}</a></p><p>Footer: Pharma Service Co. L.L.C. · Ras Al Khor, Dubai, UAE. Each recipient gets an unsubscribe link.</p><details><summary>${r.recipients.length} selected recipients — review addresses</summary>${r.recipients.map(x=>'<p>'+esc(x.email_snapshot)+'</p>').join('')}</details><p>Only active contacts with recorded permission or requested updates can receive this campaign. Eligibility is checked again immediately before sending.</p><p>One message per minute, up to 100 attempts per rolling 24 hours. Larger campaigns continue automatically. You can pause sending in Outreach.</p><label><input type="checkbox" data-approved> I reviewed this message and audience and authorize this campaign.</label><button class="button primary" data-confirm>Approve & queue campaign</button></div>`;
   d.querySelector('[data-confirm]').onclick=()=>run(d,async()=>{if(!d.querySelector('[data-approved]').checked)throw new Error('Review and tick the approval box first.');const result=await call({action:'approve',campaign_id:id,hash:r.hash,approve:true});d.querySelector('[data-error]').textContent=result.already_approved?'Already queued. It will not be queued twice.':'Campaign queued. See Drafts & sent for progress. Counts update automatically.';d.querySelector('[data-confirm]').remove();refreshPanels();window.PSC_REFRESH_MAIL?.()});
  }catch(e){d.querySelector('[data-error]').textContent=e.message}
 };
 async function mount(host){if(host.dataset.outreachMounted)return;host.dataset.outreachMounted='1';host.innerHTML='<p>Checking marketing sender…</p>';
  try{const r=await call({action:'status'}),s=r.settings;host.innerHTML=`<div class="panelHeader"><div><h2>Marketing sender</h2><p><b>outreach@pharmaservice.ae</b> · ${s.enabled?'Enabled for approved campaigns':'Paused'} · ${s.alias_status==='accepted'?'Alias verified':'Alias check needed'}</p></div><button class="button outline" data-refresh>Refresh status</button></div><details ${s.enabled?'':'open'}><summary>Sender setup</summary><ol><li>Add outreach as an alternate email for info@ in Google Admin.</li><li>In Gmail → Settings → Accounts → Send mail as, make sure outreach@pharmaservice.ae is available and verified.</li><li>Check the alias here, send the internal test, then confirm receipt and sender authentication.</li></ol><div class="wsActions"><button class="button outline" data-verify>Check alias</button><button class="button outline" data-test>Review internal test</button></div><p>Latest test: ${esc(r.test?.status||'not sent')}${r.test?.created_at?' · '+esc(r.test.created_at.slice(0,16).replace('T',' '))+' UTC':''}</p>${r.test?.status==='uncertain'?`<button class="button outline" data-reconcile="${esc(r.test.id)}">Check uncertain test in Gmail</button>`:''}<label class="commercialInboxCheck"><input type="checkbox" data-received> I received the test from outreach@ in info@.</label><label class="commercialInboxCheck"><input type="checkbox" data-auth> In Gmail’s Show original, I checked SPF, DKIM and DMARC pass for the test.</label><button class="button primary" data-enable>Enable approved campaigns</button></details><p>100 attempts per rolling 24 hours, one per minute. The alias shares info@’s Google sending allowance and reputation. No additional subscription. Replies arrive in the same mailbox.</p>${s.enabled?'<button class="button outline" data-pause>Pause campaign sending</button>':''}<p role="status" data-feedback>${esc(s.last_error?errors[s.last_error]||'Resolve the sender connection and check again.':'')}</p><details><summary>Sending issues</summary><div data-issues>Loading…</div></details>`;
   async function action(body){const f=host.querySelector('[data-feedback]');try{f.textContent='Working…';await call(body);reload()}catch(e){f.textContent=e.message}}
   const reload=()=>{host.dataset.outreachMounted='';mount(host)};host.querySelector('[data-refresh]').onclick=reload;host.querySelector('[data-verify]').onclick=()=>action({action:'verify_alias'});
   host.querySelector('[data-pause]')?.addEventListener('click',()=>action({action:'pause'}));
   host.querySelector('[data-enable]').onclick=()=>action({action:'enable',confirm_test_received:host.querySelector('[data-received]').checked,confirm_sender_authentication:host.querySelector('[data-auth]').checked});
   host.querySelector('[data-test]').onclick=()=>{const request_id=crypto.randomUUID();dialog('Approve internal sender test','<p><b>From:</b> outreach@pharmaservice.ae<br><b>To:</b> info@pharmaservice.ae<br><b>Subject:</b> PSC outreach sender test</p><p>Approved internal test of the PSC marketing alias. This message is sent only to info@pharmaservice.ae. No campaign or customer email has been sent.</p><button class="button primary" data-confirm>Approve & send this test</button>',d=>d.querySelector('[data-confirm]').onclick=()=>run(d,async()=>{await call({action:'test',approve:true,request_id});d.querySelector('[data-error]').textContent='Test recorded. Check Gmail Inbox and Sent, then refresh sender status. Gmail acceptance alone does not confirm delivery.';d.querySelector('[data-confirm]').remove();reload()}))};
   host.querySelector('[data-reconcile]')?.addEventListener('click',e=>action({action:'reconcile',attempt_id:e.target.dataset.reconcile}));
   const issues=await sb.from('psc_outreach_attempts').select('id,status,error,created_at').in('status',['uncertain','failed']).order('created_at',{ascending:false}).limit(20);
   const slot=host.querySelector('[data-issues]');if(slot){slot.innerHTML=issues.error?'<p>Could not load issues. Refresh to retry.</p>':issues.data.map(x=>`<p>${esc(x.status)} · ${esc(x.created_at.slice(0,16))} · ${esc(x.error)} ${x.status==='uncertain'?`<button class="button outline" data-issue-id="${x.id}">Check Gmail record</button>`:''}</p>`).join('')||'<p>No recorded sending issues.</p>';slot.querySelectorAll('[data-issue-id]').forEach(b=>b.onclick=async()=>{try{const result=await call({action:'reconcile',attempt_id:b.dataset.issueId});host.querySelector('[data-feedback]').textContent=result.found?'Gmail sent record found. Refresh to update the history.':'No sent record found yet. This attempt remains held and will not be resent automatically.'}catch(e){host.querySelector('[data-feedback]').textContent=e.message}})}
  }catch(e){host.innerHTML=`<p>${esc(e.message)}</p><button class="button outline" data-retry>Retry sender check</button>`;host.querySelector('[data-retry]').onclick=()=>{host.dataset.outreachMounted='';mount(host)}}
 }
 function refreshPanels(){document.querySelectorAll('[data-outreach-setup]').forEach(h=>{h.dataset.outreachMounted='';mount(h)})}
 function apply(){const header=document.querySelector('.adminShell .mailDeskHeader');if(!header||!sb||window.PSC_IS_DEMO_ACCOUNT?.())return;let h=document.querySelector('[data-outreach-setup]');if(!h){h=document.createElement('section');h.className='panel';h.dataset.outreachSetup='';header.after(h)}h.hidden=!document.querySelector('[data-mail-tab="settings"].active');mount(h);document.querySelectorAll('[data-add-outreach-contact]').forEach(b=>b.onclick=()=>window.PSC_MAIL_ADD_CONTACT?.());document.querySelectorAll('[data-outreach-review]').forEach(b=>{b.onclick=()=>window.PSC_OUTREACH_REVIEW(b.dataset.outreachReview)});document.querySelectorAll('[data-outreach-stop]').forEach(b=>{b.onclick=()=>{dialog('Stop remaining campaign emails','<p>Messages already accepted by Gmail cannot be recalled. Unsent recipients will be skipped.</p><button class="button primary" data-confirm>Stop remaining emails</button>',d=>d.querySelector('[data-confirm]').onclick=()=>run(d,async()=>{await call({action:'stop',campaign_id:b.dataset.outreachStop});d.querySelector('[data-error]').textContent='Remaining emails stopped. Drafts & sent will update automatically.';d.querySelector('[data-confirm]').remove();window.PSC_REFRESH_MAIL?.()}))}})}
 // Refresh only the read-only history view; never replace an email being composed.
 setInterval(()=>{if(!document.hidden&&!document.querySelector('dialog[open]')&&document.querySelector('[data-mail-tab="history"].active'))window.PSC_REFRESH_MAIL?.()},30000);
 window.PSC_ENHANCEMENTS.createObserver(apply).observe(document.body,{childList:true,subtree:true});apply();
})();
