(() => {
 'use strict';
 const sb=window.PSC_SUPABASE,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const addDays=(s,n)=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
 const emailOf=s=>(String(s||'').match(/<([^>]+)>/)?.[1]||String(s||'')).trim().toLowerCase();
 const stages={prospect:'Prospect',contacted:'Contacted',requirements:'Requirements received',quoting:'Preparing quotation',awaiting_decision:'Awaiting decision',customer:'Customer',dormant:'Dormant',closed:'Closed'};
 function suggest(m){
  const text=String(m.body_text||'').slice(0,100000),sentences=text.split(/\n|(?<=[.!?])\s+/).map(s=>s.trim()).filter(Boolean);
  const rules=[['budget',/too expensive|over budget|lower price|discount|reduce.*price/i,'Review pricing feedback and prepare a response'],['delivery',/when.*deliver|delivery date|lead time|urgent|by (monday|tuesday|wednesday|thursday|friday)/i,'Confirm the required date and check supplier lead time'],['specification',/different size|instead of|change.*quantity|replace|specification|alternative/i,'Review the requested changes before revising the quotation'],['meeting',/meeting|appointment|call me|available.*(time|day)/i,'Arrange a time to discuss the requirement'],['approval',/purchase order|approved|go ahead|proceed/i,'Review customer authorization and funding evidence'],['quotation',/quot(?:e|ation)|price|availability|stock/i,'Review the requirement and confirm sourcing details']];
  for(const [rule,re,title] of rules){const quote=sentences.find(s=>re.test(s));if(quote)return {rule,title,excerpt:quote.slice(0,700)}}
  return {rule:'review',title:'Read the customer message and decide the next step',excerpt:sentences[0]?.slice(0,700)||m.subject||''};
 }
 function calendar(tasks){const e=s=>String(s||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//PSC//Workspace//EN','CALSCALE:GREGORIAN',...tasks.flatMap(t=>['BEGIN:VEVENT','UID:'+e(t.key)+'@pharmaservice.ae','DTSTAMP:'+stamp,'DTSTART;VALUE=DATE:'+t.due_date.replace(/-/g,''),'DTEND;VALUE=DATE:'+addDays(t.due_date,1).replace(/-/g,''),'SUMMARY:'+e(t.title),'DESCRIPTION:'+e('PSC task. Owner: '+t.owner_label+'\nhttps://pharmaservice.ae/#admin/tasks'),'END:VEVENT']),'END:VCALENDAR'].join('\r\n')+'\r\n'}
 window.PSC_WORKSPACE_UTILS={suggest,calendar,emailOf,addDays};
 let selectedRequest='',selectedCustomer='',search='',taskFilter='open',requestFilter='all';
 async function rows(table,order='created_at'){const out=[];for(let n=0;n<10000;n+=500){const r=await sb.from(table).select('*').order(order,{ascending:false}).range(n,n+499);if(r.error)throw new Error('Could not load '+table.replace(/_/g,' ')+'. Refresh and retry.');out.push(...(r.data||[]));if((r.data||[]).length<500)return out}throw new Error('This view exceeds the current workspace limit. Narrow the data before continuing.')}
 const nav=(route,label)=>`<button type="button" class="button outline" data-ws-route="${route}">${label}</button>`;
 const pill=s=>`<span class="wsPill">${esc(String(s||'new').replace(/_/g,' '))}</span>`;
 async function mount(host){
  if(host.dataset.mounted)return;host.dataset.mounted='1';
  try{
   if(!sb||window.PSC_IS_DEMO_ACCOUNT?.())throw new Error('Sign in with the PSC administrator account.');
   const session=await sb.auth.getSession(),user=session.data?.session?.user;
   if(!user)throw new Error('Please sign in again.');
   const profile=await sb.from('profiles').select('is_psc_admin').eq('user_id',user.id).maybeSingle();if(!profile.data?.is_psc_admin)throw new Error('PSC administrator access required.');
   const [contacts,tasks,actions,orders,schools,messages,notes,enquiries,drafts,custom]=await Promise.all([rows('mail_contacts'),rows('psc_crm_tasks'),rows('commercial_actions','entity_id'),rows('orders'),rows('schools'),rows('psc_mail_messages','received_at'),rows('psc_crm_notes'),rows('institutional_enquiries'),rows('psc_mail_drafts'),rows('custom_requests')]);
   if(!host.isConnected)return;
   const data={contacts,tasks,actions,orders,schools,messages,notes,enquiries,drafts};
   const allTasks=[...tasks.map(t=>({...t,key:t.id,source:'crm'})),...actions.map(a=>({...a,title:a.next_action,key:a.entity_type+'-'+a.entity_id,source:'action'}))].sort((a,b)=>a.due_date.localeCompare(b.due_date));
   const incoming=messages.filter(m=>m.direction==='inbound'&&m.review_status!=='ignored');
   const site=id=>schools.find(s=>s.id===id),contactName=c=>[c.first_name,c.last_name].filter(Boolean).join(' ')||c.email;
   const customerMessages=c=>messages.filter(m=>emailOf(m.sender)===c.email.toLowerCase()||emailOf(m.recipient)===c.email.toLowerCase());
   const requestRecords=[...incoming.filter(m=>!m.order_id).map(m=>({key:'mail:'+m.id,id:m.id,type:'mail',name:m.subject,detail:m.sender,status:m.review_status==='linked'?'reviewed':'new email',created:m.received_at})),...orders.map(o=>({key:'order:'+o.id,id:o.id,type:'order',name:o.order_number,detail:[site(o.school_id)?.name,site(o.school_id)?.campus_name].filter(Boolean).join(' · '),status:o.status,created:o.created_at})),...enquiries.map(e=>({key:'enquiry:'+e.id,id:e.id,type:'enquiry',name:e.organization||e.name,detail:e.requirement,status:e.status,created:e.created_at}))].sort((a,b)=>String(b.created).localeCompare(String(a.created)));
   requestRecords.push(...custom.map(c=>({key:'custom:'+c.id,id:c.id,type:'custom',name:'Sourcing · '+(site(c.school_id)?.name||'Unlisted requirement'),detail:c.description,status:c.status,created:c.created_at})));
   requestRecords.sort((a,b)=>String(b.created).localeCompare(String(a.created)));
   function header(title,desc,actions=''){return `<div class="wsHeader"><div><p class="wsEyebrow">PHARMA SERVICE / WORKSPACE</p><h1>${title}</h1><p>${desc}</p></div><div class="wsActions">${actions}<button class="button outline" data-ws-refresh>Refresh</button></div></div><p role="status" data-ws-status></p>`}
   function taskCards(list){return list.map(t=>`<article class="wsTask ${!t.completed&&t.due_date<today()?'overdue':''}"><label><input type="checkbox" data-task-toggle="${esc(t.key)}" ${t.completed?'checked':''}><span><b>${esc(t.title)}</b><small>${esc(t.owner_label)} · ${esc(t.due_date)}${t.due_date<today()&&!t.completed?' · Overdue':''}</small></span></label><div class="wsTaskActions"><button data-task-edit="${esc(t.key)}">Edit</button><button data-calendar="${esc(t.key)}">Add to calendar</button></div></article>`).join('')||'<div class="wsEmpty">Nothing here yet. Add a task or review a new enquiry.</div>'}
   function taskForm(t={}){return `<form data-ws-task class="wsForm"><input type="hidden" name="id" value="${esc(t.id||'')}"><label>What needs to happen?<input name="title" required maxlength="500" value="${esc(t.title||'')}" placeholder="Confirm pack sizes with the school"></label><div class="wsColumns"><label>Due date<input name="due_date" type="date" required value="${esc(t.due_date||today())}"></label><label>Owner<input name="owner_label" required maxlength="120" value="${esc(t.owner_label||'Mohamed')}"></label></div><label>Customer<select name="contact_id"><option value="">General task</option>${contacts.map(c=>`<option value="${c.id}" ${c.id===t.contact_id?'selected':''}>${esc(c.organization||contactName(c))}</option>`).join('')}</select></label><button class="button primary">${t.id?'Save changes':'Add task'}</button></form>`}
   function suggestionCard(m){const s=suggest(m),already=tasks.some(t=>t.source_message_id===m.id&&t.source_rule===s.rule);return `<article class="wsSuggestion"><small>SUGGESTED NEXT ACTION · ${esc(m.subject)}</small><h3>${esc(s.title)}</h3><blockquote>${esc(s.excerpt)}</blockquote><p>Based on wording in the email. Review the full message before acting.</p><div class="wsActions"><button data-open-request="${m.order_id?'order:'+m.order_id:'mail:'+m.id}">Open conversation</button><button data-suggest-task="${m.id}" ${already?'disabled':''}>${already?'Task already created':'Review & schedule task'}</button></div></article>`}
   function todayView(){const due=allTasks.filter(t=>!t.completed&&t.due_date<=today()),fresh=incoming.filter(m=>m.review_status==='unmatched'),pending=drafts.filter(d=>d.status==='draft');return header('Today','Your priorities, customer replies and next steps in one place.',nav('admin/tasks','Add a task'))+`<div class="wsStats"><button data-ws-route="admin/tasks"><b>${due.length}</b><span>Due or overdue</span></button><button data-ws-route="admin/requests"><b>${fresh.length}</b><span>Emails to review</span></button><button data-ws-route="admin/requests"><b>${orders.filter(o=>!['delivered','cancelled','closed'].includes(o.status)).length}</b><span>Open requests</span></button><button data-show-drafts><b>${pending.length}</b><span>Email drafts</span></button></div><div class="wsSplit"><section class="wsPanel"><h2>Your next actions</h2>${taskCards(due.slice(0,12))}${nav('admin/tasks','View full agenda')}</section><section class="wsPanel"><h2>Customer replies to consider</h2>${incoming.slice(0,4).map(suggestionCard).join('')||'<p>Label relevant emails PSC-Procurement in Gmail to bring them into Requests.</p>'}</section></div><section class="wsPanel"><h2>Quick start</h2><div class="wsActions">${nav('admin/requests','Review a request')}${nav('admin/customers','Find or add a customer')}${nav('admin/mail','Prepare an introduction or newsletter')}</div></section>`}
   function requestsView(){const record=requestRecords.find(r=>r.key===selectedRequest);if(record)return requestDetail(record);let list=requestRecords.filter(r=>(requestFilter==='all'||r.type===requestFilter)&&[r.name,r.detail,r.status].join(' ').toLowerCase().includes(search.toLowerCase()));return header('Requests','Choose one requirement to see its items, conversation and next action.')+`<div class="wsToolbar"><input aria-label="Search requests" data-ws-search placeholder="Search customer, reference or requirement" value="${esc(search)}"><select data-request-filter><option value="all">All requests</option><option value="mail">Incoming email</option><option value="order">Portal requests</option><option value="enquiry">Website enquiries</option></select></div><div class="wsList">${list.map(r=>`<button class="wsRequest" data-open-request="${r.key}"><span><small>${esc(r.type==='mail'?'EMAIL':r.type==='order'?'REQUEST':'ENQUIRY')}</small><b>${esc(r.name)}</b><p>${esc(r.detail?.slice(0,160))}</p></span><span>${pill(r.status)}<small>${esc(String(r.created).slice(0,10))}</small><strong>Open →</strong></span></button>`).join('')||'<div class="wsEmpty">No requests match this view.</div>'}</div>`}
   function requestDetail(r){const order=orders.find(o=>o.id===r.id),message=messages.find(m=>m.id===r.id),enquiry=enquiries.find(e=>e.id===r.id);return header(esc(r.name),esc(r.detail?.slice(0,200)||''),'<button class="button outline" data-back-requests>← All requests</button>')+`<div class="wsJourney"><span class="active">1. Review requirement</span><span>2. Source & quote</span><span>3. Customer decision</span><span>4. Fulfilment</span></div><section class="wsPanel"><h2>Next step</h2><p>${r.type==='mail'?'Open the item review below, check the attachment and choose the products to source.':r.type==='enquiry'?'Review the requirement, record a follow-up and clarify any missing details.':'Open the quotation builder to review item costs and terms. Keep your next action and correspondence here.'}</p><div class="wsActions">${order?`<button class="button primary" data-open-builder="${r.id}">Open items & quotation</button>`:''}<button data-request-task="${r.key}">Schedule a follow-up</button>${message?'<button data-contact-from="'+message.id+'">Create customer contact</button>':''}</div></section>${message?suggestionCard(message):''}${enquiry?`<section class="wsPanel"><h2>Customer requirement</h2><p>${esc(enquiry.name)} · ${esc(enquiry.contact_email)} · ${esc(enquiry.contact_number)}</p><p class="wsPre">${esc(enquiry.requirement)}</p></section>`:''}<section data-commercial-inbox ${order?'data-entity-id="'+r.id+'" data-order-id="'+r.id+'"':message?'data-message-id="'+r.id+'"':'data-entity-id="'+r.id+'" data-no-mail="true"'}></section>`}
   function contactForm(c={}){return `<form data-ws-contact class="wsForm"><input type="hidden" name="id" value="${esc(c.id||'')}"><div class="wsColumns"><label>Contact name<input name="first_name" required maxlength="200" value="${esc(c.first_name||'')}"></label><label>Institution / company<input name="organization" maxlength="300" value="${esc(c.organization||'')}"></label></div><label>Email<input name="email" type="email" required maxlength="254" value="${esc(c.email||'')}"></label><div class="wsColumns"><label>Phone<input name="phone" maxlength="100" value="${esc(c.phone||'')}"></label><label>Role<input name="role" maxlength="200" value="${esc(c.role||'')}"></label></div><label>Website<input name="website" type="url" maxlength="500" placeholder="https://" value="${esc(c.website||'')}"></label><label>Journey stage<select name="journey_stage">${Object.entries(stages).map(([k,v])=>`<option value="${k}" ${k===c.journey_stage?'selected':''}>${v}</option>`).join('')}</select></label><label>Link to a verified customer site<select name="school_id"><option value="">Prospect / no site linked</option>${schools.map(s=>`<option value="${s.id}" ${s.id===c.school_id?'selected':''}>${esc(s.name)} · ${esc(s.campus_name||'')}</option>`).join('')}</select></label><button class="button primary">Save customer contact</button><p>Marketing permissions are managed separately in Outreach. Adding a contact does not subscribe them.</p></form>`}
   function customersView(){const c=contacts.find(c=>c.id===selectedCustomer);if(c){const mail=customerMessages(c),linked=orders.filter(o=>c.school_id&&o.school_id===c.school_id);return header(esc(c.organization||contactName(c)),esc(contactName(c)+' · '+c.email),'<button data-back-customers>← All customers</button>')+`<div class="wsSplit"><section class="wsPanel"><h2>Contact & journey</h2>${contactForm(c)}</section><section class="wsPanel"><h2>Activity & next actions</h2>${pill(stages[c.journey_stage]||'Prospect')}<p>${mail.length} matching messages · ${linked.length} linked requests</p>${taskCards(allTasks.filter(t=>t.contact_id===c.id&&!t.completed))}<button data-customer-task="${c.id}">Add follow-up</button><h3>Requests</h3>${linked.map(o=>`<button data-open-request="order:${o.id}">${esc(o.order_number)} · ${esc(o.status)}</button>`).join('')||'<p>No linked request yet.</p>'}<h3>Notes</h3><form data-ws-note><textarea name="note" required maxlength="5000" placeholder="Meeting outcome, preferences or useful context"></textarea><button class="button outline">Add note</button></form>${notes.filter(n=>n.contact_id===c.id).map(n=>`<article class="wsNote"><small>${esc(n.created_at.slice(0,10))}</small><p>${esc(n.note)}</p></article>`).join('')}<h3>Correspondence</h3>${mail.map(m=>`<details class="wsNote"><summary>${esc(m.subject)} · ${esc(m.received_at.slice(0,10))}</summary><p class="wsPre">${esc(m.body_text)}</p>${m.direction==='inbound'?suggestionCard(m):''}</details>`).join('')||'<p>Messages are matched by this exact email address. Confirm other addresses manually.</p>'}</section></div>`}
    return header('Customers','Your prospects, contacts and customer journey.', '<button class="button primary" data-new-customer>Add contact</button>')+`<div class="wsToolbar"><input data-ws-search aria-label="Search customers" placeholder="Search institution, name, email or role" value="${esc(search)}"></div><div class="wsCustomerGrid">${contacts.filter(c=>[c.organization,c.first_name,c.last_name,c.email,c.role].join(' ').toLowerCase().includes(search.toLowerCase())).map(c=>`<button class="wsCustomer" data-open-customer="${c.id}">${pill(stages[c.journey_stage]||'Prospect')}<h2>${esc(c.organization||contactName(c))}</h2><p>${esc(contactName(c))}</p><small>${esc(c.email)}</small><p>${customerMessages(c).length} messages · ${tasks.filter(t=>t.contact_id===c.id&&!t.completed).length} open tasks</p></button>`).join('')||'<div class="wsEmpty">Add your first prospect or customer contact. Existing outreach contacts appear here automatically.</div>'}</div><details class="wsPanel"><summary>Existing customer sites (${schools.length})</summary>${schools.map(s=>`<p>${esc(s.name)} · ${esc(s.campus_name||'')} · ${esc(s.quote_email||'No quotation contact recorded')}</p>`).join('')}</details>`}
   function tasksView(){const open=allTasks.filter(t=>!t.completed),list=allTasks.filter(t=>taskFilter==='all'||taskFilter==='done'?taskFilter==='all'||t.completed:taskFilter==='overdue'?!t.completed&&t.due_date<today():taskFilter==='open'?!t.completed:t.due_date===taskFilter&&!t.completed);return header('Tasks & calendar','Your follow-ups, with dates and a clear owner.', '<button data-export-calendar>Export open tasks (.ics)</button>')+`<div class="wsWeek">${Array.from({length:7},(_,i)=>{const day=addDays(today(),i);return `<button data-day="${day}"><small>${new Intl.DateTimeFormat('en',{weekday:'short',timeZone:'Asia/Dubai'}).format(new Date(day+'T12:00Z'))}</small><b>${day.slice(8)}</b><span>${open.filter(t=>t.due_date===day).length} tasks</span></button>`}).join('')}</div><div class="wsSplit"><section class="wsPanel"><div class="wsActions"><button data-task-filter="open">Open</button><button data-task-filter="overdue">Overdue</button><button data-task-filter="done">Completed</button><button data-task-filter="all">All</button></div>${taskCards(list)}<p class="wsMuted">Calendar links and exports add a copy to your calendar. Changes are managed here; two-way calendar sync is not connected.</p></section><section class="wsPanel"><h2>Add a task</h2>${taskForm()}</section></div>`}
   function resourcesView(){return header('Products & suppliers','Catalogue and sourcing tools, grouped in one place.')+`<div class="wsResourceGrid">${[['admin/products','Product catalogue','Products, specifications, images and commercial details'],['admin/family-options','Supplier options','Review product alternatives and supplier candidates'],['admin/supplier-feed','Supplier data','Import and review supplier catalogue information'],['admin/storefront','Website catalogue','Manage which products appear on the website']].map(([r,t,d])=>`<button class="wsResource" data-ws-route="${r}"><h2>${t}</h2><p>${d}</p><span>Open →</span></button>`).join('')}</div>`}
   function settingsView(){return header('Settings','Mailbox connection and occasional operational setup.')+`<section data-commercial-inbox data-mail-settings="true"></section><section class="wsPanel"><h2>Operations</h2>${nav('admin/fulfilment','Fulfilment rules')}<p>Bank transfer remains the payment method. Customer payments are not collected online.</p></section><section class="wsPanel"><h2>Marketing delivery</h2><p>Prospect introductions and Workshop newsletters can be prepared and saved in Outreach. Use Outreach to verify outreach@pharmaservice.ae, run an internal test and enable approved campaigns. Marketing uses the existing Gmail connection with a separate queue and shared mailbox limits.</p>${nav('admin/mail','Open Outreach')}</section>`}
   function render(){const v=host.dataset.pscWorkspace;host.innerHTML=({today:todayView,requests:requestsView,customers:customersView,tasks:tasksView,resources:resourcesView,settings:settingsView}[v]||todayView)();bind();if(v==='requests'&&!selectedRequest){const f=host.querySelector('[data-request-filter]');f.insertAdjacentHTML('beforeend','<option value="custom">Unlisted sourcing</option>');f.value=requestFilter}if(v==='requests'&&selectedRequest){const r=requestRecords.find(r=>r.key===selectedRequest),journey=host.querySelector('.wsJourney');if(journey){journey.setAttribute('aria-label','Procurement workflow; current status: '+r.status);journey.querySelector('.active')?.classList.remove('active');journey.insertAdjacentHTML('beforebegin','<p>'+pill(r.status)+'</p>')}}}
   function status(s){host.querySelector('[data-ws-status]').textContent=s}
   async function act(fn){try{await fn()}catch(e){status(e.message||'Could not save. Please retry.')}}
   async function write(table,payload,id){const q=id?sb.from(table).update(payload).eq('id',id):sb.from(table).insert(payload);const r=await q.select().single();if(r.error)throw new Error(r.error.code==='23505'?'This record already exists. Refresh to see it.':'Not saved. Check the fields and retry.');if(!r.data)throw new Error('Save was not acknowledged.');return r.data}
   const reload=()=>{host.dataset.mounted='';mount(host)};
   function dialog(title,body,onReady){const d=document.createElement('dialog');d.className='wsDialog';d.innerHTML=`<div class="wsDialogHead"><h2>${title}</h2><button data-dialog-close aria-label="Close">×</button></div>${body}<p role="status" data-dialog-error></p>`;document.body.append(d);d.querySelector('[data-dialog-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();onReady?.(d)}
   function taskEditor(t={},extra={}){dialog('Schedule next action',taskForm(t),d=>{d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{const payload={title:String(f.get('title')).trim(),due_date:f.get('due_date'),owner_label:String(f.get('owner_label')).trim(),contact_id:f.get('contact_id')||null,updated_by:user.id,updated_at:new Date().toISOString(),...extra};if(t.source==='action'){const r=await sb.from('commercial_actions').update({next_action:payload.title,due_date:payload.due_date,owner_label:payload.owner_label,updated_by:user.id,updated_at:payload.updated_at}).eq('entity_type',t.entity_type).eq('entity_id',t.entity_id).select().single();if(r.error||!r.data)throw new Error('Could not save this follow-up.')}else await write('psc_crm_tasks',payload,t.id);d.close();reload()}catch(err){d.querySelector('[data-dialog-error]').textContent=err.message}}})}
   function bind(){
    host.querySelectorAll('[data-ws-route]').forEach(b=>b.onclick=()=>window.PSC_NAVIGATE(b.dataset.wsRoute));host.querySelector('[data-ws-refresh]').onclick=reload;
    host.querySelector('[data-ws-search]')?.addEventListener('input',e=>{search=e.target.value;const start=e.target.selectionStart;render();const input=host.querySelector('[data-ws-search]');input.focus();input.setSelectionRange(start,start)});
    host.querySelector('[data-request-filter]')?.addEventListener('change',e=>{requestFilter=e.target.value;render()});
    host.querySelectorAll('[data-open-request]').forEach(b=>b.onclick=()=>{selectedRequest=b.dataset.openRequest;search='';if(host.dataset.pscWorkspace==='requests')render();else window.PSC_NAVIGATE('admin/requests')});
    host.querySelector('[data-back-requests]')?.addEventListener('click',()=>{selectedRequest='';render()});
    host.querySelector('[data-open-builder]')?.addEventListener('click',e=>window.PSC_WORKSPACE_OPEN_REQUEST(e.currentTarget.dataset.openBuilder));
    host.querySelectorAll('[data-task-toggle]').forEach(b=>b.onchange=()=>act(async()=>{const t=allTasks.find(t=>t.key===b.dataset.taskToggle);if(t.source==='crm')await write('psc_crm_tasks',{completed:b.checked,updated_by:user.id,updated_at:new Date().toISOString()},t.id);else{const r=await sb.from('commercial_actions').update({completed:b.checked,updated_by:user.id,updated_at:new Date().toISOString()}).eq('entity_type',t.entity_type).eq('entity_id',t.entity_id).select().single();if(r.error||!r.data)throw new Error('Could not update the follow-up.')}reload()}));
    host.querySelectorAll('[data-task-edit]').forEach(b=>b.onclick=()=>taskEditor(allTasks.find(t=>t.key===b.dataset.taskEdit)));
    host.querySelectorAll('[data-calendar]').forEach(b=>b.onclick=()=>{const t=allTasks.find(t=>t.key===b.dataset.calendar);const p=new URLSearchParams({action:'TEMPLATE',text:t.title,dates:t.due_date.replace(/-/g,'')+'/'+addDays(t.due_date,1).replace(/-/g,''),details:'PSC task · '+t.owner_label+'\nhttps://pharmaservice.ae/#admin/tasks'});window.open('https://calendar.google.com/calendar/render?'+p,'_blank','noopener,noreferrer')});
    host.querySelector('[data-export-calendar]')?.addEventListener('click',()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([calendar(allTasks.filter(t=>!t.completed))],{type:'text/calendar;charset=utf-8'}));a.href=url;a.download='PSC-follow-ups.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
    host.querySelectorAll('[data-day],[data-task-filter]').forEach(b=>b.onclick=()=>{taskFilter=b.dataset.day||b.dataset.taskFilter;render()});
    host.querySelectorAll('[data-suggest-task]').forEach(b=>b.onclick=()=>{const m=messages.find(m=>m.id===b.dataset.suggestTask),s=suggest(m),matches=contacts.filter(c=>c.email.toLowerCase()===emailOf(m.sender));taskEditor({title:s.title,contact_id:matches.length===1?matches[0].id:null},{source_message_id:m.id,source_rule:s.rule,source_excerpt:s.excerpt,order_id:m.order_id||null})});
    host.querySelectorAll('[data-customer-task]').forEach(b=>b.onclick=()=>taskEditor({contact_id:b.dataset.customerTask}));
    host.querySelector('[data-request-task]')?.addEventListener('click',()=>{const r=requestRecords.find(r=>r.key===selectedRequest);taskEditor({title:'Follow up: '+r.name},r.type==='order'?{order_id:r.id}:r.type==='mail'?{source_message_id:r.id}:{})});
    host.querySelectorAll('[data-open-customer]').forEach(b=>b.onclick=()=>{selectedCustomer=b.dataset.openCustomer;search='';render()});host.querySelector('[data-back-customers]')?.addEventListener('click',()=>{selectedCustomer='';render()});
    const bindContact=(form,d)=>{form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),id=f.get('id'),payload=Object.fromEntries(['first_name','organization','email','phone','role','website','journey_stage'].map(k=>[k,String(f.get(k)||'').trim()]));payload.email=payload.email.toLowerCase();payload.school_id=f.get('school_id')||null;payload.updated_at=new Date().toISOString();if(!id){payload.marketing_basis='not_set';payload.status='paused';payload.created_by=user.id}try{const saved=await write('mail_contacts',payload,id);selectedCustomer=saved.id;d?.close();if(host.dataset.pscWorkspace!=='customers')window.PSC_NAVIGATE('admin/customers');else reload()}catch(err){(d?.querySelector('[data-dialog-error]')||host.querySelector('[data-ws-status]')).textContent=err.message}}};
    host.querySelector('[data-ws-contact]')&&bindContact(host.querySelector('[data-ws-contact]'));
    host.querySelector('[data-new-customer]')?.addEventListener('click',()=>dialog('Add customer or prospect',contactForm(),d=>bindContact(d.querySelector('form'),d)));
    host.querySelector('[data-contact-from]')?.addEventListener('click',e=>{const m=messages.find(m=>m.id===e.currentTarget.dataset.contactFrom),mail=emailOf(m.sender),found=contacts.find(c=>c.email.toLowerCase()===mail);if(found){selectedCustomer=found.id;window.PSC_NAVIGATE('admin/customers');return}dialog('Review customer details',contactForm({first_name:m.sender.replace(/<.*>/,'').trim(),email:mail}),d=>bindContact(d.querySelector('form'),d))});
    host.querySelector('[data-ws-note]')?.addEventListener('submit',e=>{e.preventDefault();act(async()=>{await write('psc_crm_notes',{contact_id:selectedCustomer,note:e.target.elements.note.value.trim(),created_by:user.id});reload()})});
    host.querySelector('[data-ws-task]')?.addEventListener('submit',e=>{e.preventDefault();act(async()=>{const f=new FormData(e.target);await write('psc_crm_tasks',{title:String(f.get('title')).trim(),due_date:f.get('due_date'),owner_label:String(f.get('owner_label')).trim(),contact_id:f.get('contact_id')||null,updated_by:user.id});reload()})});
    host.querySelector('[data-show-drafts]')?.addEventListener('click',()=>dialog('Email drafts awaiting review',drafts.filter(d=>d.status==='draft').map(d=>`<article class="wsNote"><h3>${esc(d.subject)}</h3><p>${esc(d.recipient)}</p><button data-draft-source="${d.order_id?'order:'+d.order_id:d.intake_message_id?'mail:'+d.intake_message_id:''}">Open request</button></article>`).join('')||'<p>No pending drafts.</p>',d=>d.querySelectorAll('[data-draft-source]').forEach(b=>b.onclick=()=>{if(!b.dataset.draftSource){d.close();window.PSC_NAVIGATE('admin/settings');return}selectedRequest=b.dataset.draftSource;d.close();window.PSC_NAVIGATE('admin/requests')})));
   }
   render();
  }catch(e){host.innerHTML=`<div class="wsPanel"><h1>Workspace unavailable</h1><p>${esc(e.message)}</p><button data-ws-retry>Retry</button></div>`;host.querySelector('[data-ws-retry]').onclick=()=>{host.dataset.mounted='';mount(host)}}
 }
 function apply(){const host=document.querySelector('[data-psc-workspace]');if(host)mount(host)}
 window.PSC_ENHANCEMENTS.createObserver(apply).observe(document.body,{childList:true,subtree:true});apply();
})();
